import {
  Course,
  Module,
  Lesson,
  Assignment,
  Student,
  Grade,
  Quiz,
  Announcement,
  DiscussionThread,
  ScheduleEvent,
} from "@/lib/instructor-types";

export const MOCK_INSTRUCTOR_COURSES: Course[] = [
  {
    id: "course-1",
    code: "CS101",
    title: "Introduction to Computer Science",
    description: "Fundamentals of programming and computational thinking",
    semester: "Spring 2024",
    enrollmentCount: 45,
    thumbnail: "/placeholder.svg?height=200&width=300",
    status: "active",
    credits: 3,
    maxStudents: 50,
  },
  {
    id: "course-2",
    code: "CS201",
    title: "Data Structures",
    description: "Advanced concepts in data organization and algorithms",
    semester: "Spring 2024",
    enrollmentCount: 38,
    thumbnail: "/placeholder.svg?height=200&width=300",
    status: "active",
    credits: 4,
    maxStudents: 40,
  },
  {
    id: "course-3",
    code: "CS301",
    title: "Web Development",
    description: "Building modern web applications",
    semester: "Spring 2024",
    enrollmentCount: 52,
    thumbnail: "/placeholder.svg?height=200&width=300",
    status: "active",
    credits: 3,
    maxStudents: 60,
  },
];

export const MOCK_MODULES: Module[] = [
  {
    id: "module-1",
    title: "Week 1: Fundamentals",
    week: 1,
    order: 1,
    lessons: [],
  },
  {
    id: "module-2",
    title: "Week 2: Variables & Control Flow",
    week: 2,
    order: 2,
    lessons: [],
  },
  {
    id: "module-3",
    title: "Week 3: Functions & Methods",
    week: 3,
    order: 3,
    lessons: [],
  },
];

export const MOCK_LESSONS: Lesson[] = [
  {
    id: "lesson-1",
    courseId: "course-1",
    moduleId: "module-1",
    title: "What is Computer Science?",
    description: "Introduction to the field and its applications",
    type: "video",
    duration: 15,
    videoUrl: "https://example.com/video1",
    order: 1,
    published: true,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "lesson-2",
    courseId: "course-1",
    moduleId: "module-1",
    title: "Setup Your First Program",
    description: "Environment setup and first Hello World",
    type: "pdf",
    resourceUrl: "https://example.com/setup.pdf",
    order: 2,
    published: true,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "lesson-3",
    courseId: "course-1",
    moduleId: "module-2",
    title: "Variables & Data Types",
    description: "Understanding variables and basic data types",
    type: "video",
    duration: 25,
    videoUrl: "https://example.com/video2",
    order: 1,
    published: true,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "lesson-4",
    courseId: "course-1",
    moduleId: "module-2",
    title: "Control Flow Quiz",
    description: "Test your understanding",
    type: "quiz",
    order: 2,
    published: true,
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-18"),
  },
];

export const MOCK_ASSIGNMENTS: Assignment[] = [
  {
    id: "assign-1",
    courseId: "course-1",
    title: "Hello World Program",
    description: "Create your first program",
    type: "file",
    dueDate: new Date("2024-02-15"),
    maxScore: 100,
    status: "active",
    submissions: [
      {
        id: "sub-1",
        assignmentId: "assign-1",
        studentId: "student-1",
        submissionDate: new Date("2024-02-14"),
        score: 95,
        feedback: "Excellent work!",
        status: "graded",
      },
      {
        id: "sub-2",
        assignmentId: "assign-1",
        studentId: "student-2",
        submissionDate: new Date("2024-02-13"),
        status: "submitted",
      },
    ],
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "assign-2",
    courseId: "course-1",
    title: "Control Flow Assignment",
    description: "Implement control flow concepts",
    type: "file",
    dueDate: new Date("2024-02-28"),
    maxScore: 100,
    status: "active",
    submissions: [],
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "assign-3",
    courseId: "course-1",
    title: "Data Structures Practice",
    description: "Practice implementing basic data structures",
    type: "essay",
    dueDate: new Date("2024-03-15"),
    maxScore: 100,
    status: "draft",
    submissions: [],
    createdAt: new Date("2024-02-15"),
  },
];

export const MOCK_STUDENTS: Student[] = [
  {
    id: "student-1",
    name: "Alice Johnson",
    email: "alice.johnson@school.edu",
    studentId: "STU001",
    avatar: "/placeholder.svg?height=40&width=40",
    status: "active",
    enrolledCourses: ["course-1", "course-2"],
    joinDate: new Date("2024-01-15"),
    lastActivity: new Date("2024-02-20"),
  },
  {
    id: "student-2",
    name: "Bob Smith",
    email: "bob.smith@school.edu",
    studentId: "STU002",
    avatar: "/placeholder.svg?height=40&width=40",
    status: "active",
    enrolledCourses: ["course-1"],
    joinDate: new Date("2024-01-15"),
    lastActivity: new Date("2024-02-18"),
  },
  {
    id: "student-3",
    name: "Carol Davis",
    email: "carol.davis@school.edu",
    studentId: "STU003",
    avatar: "/placeholder.svg?height=40&width=40",
    status: "active",
    enrolledCourses: ["course-1", "course-3"],
    joinDate: new Date("2024-01-15"),
    lastActivity: new Date("2024-02-19"),
  },
  {
    id: "student-4",
    name: "David Wilson",
    email: "david.wilson@school.edu",
    studentId: "STU004",
    avatar: "/placeholder.svg?height=40&width=40",
    status: "pending",
    enrolledCourses: ["course-2"],
    joinDate: new Date("2024-02-10"),
  },
  {
    id: "student-5",
    name: "Eve Martinez",
    email: "eve.martinez@school.edu",
    studentId: "STU005",
    avatar: "/placeholder.svg?height=40&width=40",
    status: "inactive",
    enrolledCourses: ["course-1"],
    joinDate: new Date("2024-01-15"),
    lastActivity: new Date("2024-01-30"),
  },
];

export const MOCK_GRADES: Grade[] = [
  {
    id: "grade-1",
    courseId: "course-1",
    studentId: "student-1",
    assignmentId: "assign-1",
    score: 95,
    maxScore: 100,
    gradedAt: new Date("2024-02-15"),
    feedback: "Excellent implementation!",
  },
  {
    id: "grade-2",
    courseId: "course-1",
    studentId: "student-2",
    assignmentId: "assign-1",
    score: 87,
    maxScore: 100,
    gradedAt: new Date("2024-02-16"),
    feedback: "Good work, minor improvements needed",
  },
  {
    id: "grade-3",
    courseId: "course-1",
    studentId: "student-3",
    assignmentId: "assign-1",
    score: 92,
    maxScore: 100,
    gradedAt: new Date("2024-02-15"),
    feedback: "Great job!",
  },
];

export const MOCK_QUIZZES: Quiz[] = [
  {
    id: "quiz-1",
    courseId: "course-1",
    title: "Week 1 Assessment",
    description: "Test your understanding of week 1 concepts",
    timeLimit: 30,
    passingScore: 70,
    published: true,
    dueDate: new Date("2024-02-18"),
    questions: [
      {
        id: "q1",
        quizId: "quiz-1",
        type: "mcq",
        content: "What is a variable?",
        points: 10,
        options: ["A container for data", "A function", "A loop", "A condition"],
        correctAnswer: "A container for data",
        order: 1,
      },
      {
        id: "q2",
        quizId: "quiz-1",
        type: "true-false",
        content: "Python is a compiled language",
        points: 5,
        correctAnswer: "false",
        order: 2,
      },
    ],
    attempts: [
      {
        id: "attempt-1",
        quizId: "quiz-1",
        studentId: "student-1",
        score: 15,
        maxScore: 15,
        startTime: new Date("2024-02-18 10:00"),
        endTime: new Date("2024-02-18 10:25"),
        answers: { q1: "A container for data", q2: "false" },
      },
    ],
    createdAt: new Date("2024-02-10"),
  },
];

export const MOCK_ANNOUNCEMENTS: Announcement[] = [
  {
    id: "announce-1",
    courseId: "course-1",
    title: "Welcome to CS101",
    content: "Welcome to Introduction to Computer Science. Let's have a great semester!",
    publishedAt: new Date("2024-01-15"),
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "announce-2",
    courseId: "course-1",
    title: "Assignment 1 Posted",
    content: "Assignment 1 is now available. Due on February 15th.",
    publishedAt: new Date("2024-02-01"),
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "announce-3",
    courseId: "course-1",
    title: "Exam Schedule",
    content: "Final exam is scheduled for May 20th from 2-4 PM",
    scheduled: true,
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-02-15"),
  },
];

export const MOCK_DISCUSSIONS: DiscussionThread[] = [
  {
    id: "discuss-1",
    courseId: "course-1",
    title: "How do I install Python?",
    content: "I'm having trouble installing Python on my computer. Can someone help?",
    authorId: "student-2",
    authorName: "Bob Smith",
    isPinned: false,
    views: 24,
    replies: [
      {
        id: "reply-1",
        threadId: "discuss-1",
        content: "Follow this guide: https://example.com/python-install",
        authorId: "instructor-1",
        authorName: "Dr. Jane Smith",
        likes: 8,
        createdAt: new Date("2024-02-12"),
      },
    ],
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "discuss-2",
    courseId: "course-1",
    title: "Can we extend the deadline?",
    content: "The assignment deadline is very tight for those with other projects. Can we get more time?",
    authorId: "student-1",
    authorName: "Alice Johnson",
    isPinned: false,
    views: 18,
    replies: [
      {
        id: "reply-2",
        threadId: "discuss-2",
        content: "The deadline has been extended to February 20th.",
        authorId: "instructor-1",
        authorName: "Dr. Jane Smith",
        likes: 12,
        createdAt: new Date("2024-02-11"),
      },
    ],
    createdAt: new Date("2024-02-10"),
  },
];

export const MOCK_SCHEDULE_EVENTS: ScheduleEvent[] = [
  {
    id: "event-1",
    courseId: "course-1",
    title: "Lecture: Introduction to Variables",
    type: "lecture",
    startTime: new Date("2024-02-22 10:00"),
    endTime: new Date("2024-02-22 11:30"),
    location: "Room 101",
  },
  {
    id: "event-2",
    courseId: "course-1",
    title: "Assignment 1 Due",
    type: "deadline",
    startTime: new Date("2024-02-15 23:59"),
    endTime: new Date("2024-02-15 23:59"),
  },
  {
    id: "event-3",
    courseId: "course-1",
    title: "Midterm Exam",
    type: "exam",
    startTime: new Date("2024-03-21 14:00"),
    endTime: new Date("2024-03-21 16:00"),
    location: "Exam Hall",
  },
  {
    id: "event-4",
    courseId: "course-1",
    title: "Office Hours",
    type: "office-hours",
    startTime: new Date("2024-02-21 16:00"),
    endTime: new Date("2024-02-21 18:00"),
    location: "Office 304",
  },
];
