import { Tenant, Subscription, Transaction, UserRecord, Course, ChartData } from './types'

export const mockTenants: Tenant[] = [
  {
    id: '1',
    name: 'Lincoln High School',
    domain: 'lincoln.edu',
    plan: 'enterprise',
    status: 'active',
    students: 2400,
    courses: 45,
    createdAt: new Date('2023-01-15'),
    lastLogin: new Date(),
  },
  {
    id: '2',
    name: 'Tech Academy',
    domain: 'techacademy.io',
    plan: 'pro',
    status: 'active',
    students: 1200,
    courses: 28,
    createdAt: new Date('2023-03-20'),
    lastLogin: new Date(Date.now() - 86400000),
  },
  {
    id: '3',
    name: 'Creative Institute',
    domain: 'creative-inst.com',
    plan: 'starter',
    status: 'trial',
    students: 450,
    courses: 12,
    createdAt: new Date('2024-11-01'),
  },
  {
    id: '4',
    name: 'Global Learning Hub',
    domain: 'globallearning.net',
    plan: 'enterprise',
    status: 'active',
    students: 5600,
    courses: 92,
    createdAt: new Date('2022-06-10'),
    lastLogin: new Date(Date.now() - 3600000),
  },
  {
    id: '5',
    name: 'University Online',
    domain: 'uni-online.edu',
    plan: 'pro',
    status: 'active',
    students: 3200,
    courses: 64,
    createdAt: new Date('2023-08-05'),
    lastLogin: new Date(Date.now() - 7200000),
  },
]

export const mockSubscriptions: Subscription[] = [
  {
    id: 'sub_1',
    tenantId: '1',
    planId: 'enterprise',
    status: 'active',
    amount: 999,
    billingCycle: 'monthly',
    currentPeriodStart: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    currentPeriodEnd: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    nextBillingDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'sub_2',
    tenantId: '2',
    planId: 'pro',
    status: 'active',
    amount: 499,
    billingCycle: 'monthly',
    currentPeriodStart: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
    currentPeriodEnd: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
    nextBillingDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'sub_3',
    tenantId: '3',
    planId: 'starter',
    status: 'active',
    amount: 99,
    billingCycle: 'monthly',
    currentPeriodStart: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    currentPeriodEnd: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
  },
]

export const mockTransactions: Transaction[] = [
  {
    id: 'txn_1',
    tenantId: '1',
    amount: 999,
    currency: 'USD',
    type: 'payment',
    status: 'completed',
    description: 'Monthly subscription - Enterprise Plan',
    createdAt: new Date(Date.now() - 86400000),
  },
  {
    id: 'txn_2',
    tenantId: '2',
    amount: 499,
    currency: 'USD',
    type: 'payment',
    status: 'completed',
    description: 'Monthly subscription - Pro Plan',
    createdAt: new Date(Date.now() - 172800000),
  },
  {
    id: 'txn_3',
    tenantId: '4',
    amount: 100,
    currency: 'USD',
    type: 'refund',
    status: 'completed',
    description: 'Course purchase refund',
    createdAt: new Date(Date.now() - 259200000),
  },
  {
    id: 'txn_4',
    tenantId: '1',
    amount: 50,
    currency: 'USD',
    type: 'adjustment',
    status: 'completed',
    description: 'Credit adjustment - Support ticket #2345',
    createdAt: new Date(Date.now() - 345600000),
  },
  {
    id: 'txn_5',
    tenantId: '5',
    amount: 499,
    currency: 'USD',
    type: 'payment',
    status: 'pending',
    description: 'Monthly subscription - Pro Plan',
    createdAt: new Date(Date.now() - 3600000),
  },
]

export const mockUsers: UserRecord[] = [
  {
    id: 'user_1',
    email: 'admin@lincoln.edu',
    role: 'admin',
    tenantId: '1',
    status: 'active',
    createdAt: new Date('2023-01-15'),
    lastLogin: new Date(),
  },
  {
    id: 'user_2',
    email: 'instructor@lincoln.edu',
    role: 'instructor',
    tenantId: '1',
    status: 'active',
    createdAt: new Date('2023-02-01'),
    lastLogin: new Date(Date.now() - 3600000),
  },
  {
    id: 'user_3',
    email: 'student@lincoln.edu',
    role: 'student',
    tenantId: '1',
    status: 'active',
    createdAt: new Date('2023-03-15'),
    lastLogin: new Date(Date.now() - 7200000),
  },
  {
    id: 'user_4',
    email: 'admin@tech.io',
    role: 'admin',
    tenantId: '2',
    status: 'active',
    createdAt: new Date('2023-03-20'),
    lastLogin: new Date(Date.now() - 86400000),
  },
  {
    id: 'user_5',
    email: 'suspended@uni.edu',
    role: 'student',
    tenantId: '5',
    status: 'suspended',
    createdAt: new Date('2023-08-15'),
  },
]

export const mockCourses: Course[] = [
  {
    id: 'course_1',
    tenantId: '1',
    title: 'Introduction to Computer Science',
    instructor: 'Dr. James Wilson',
    students: 240,
    status: 'published',
    createdAt: new Date('2023-01-20'),
  },
  {
    id: 'course_2',
    tenantId: '1',
    title: 'Advanced Mathematics',
    instructor: 'Prof. Sarah Johnson',
    students: 185,
    status: 'published',
    createdAt: new Date('2023-02-10'),
  },
  {
    id: 'course_3',
    tenantId: '2',
    title: 'Web Development Bootcamp',
    instructor: 'Mark Chen',
    students: 320,
    status: 'published',
    createdAt: new Date('2023-03-15'),
  },
  {
    id: 'course_4',
    tenantId: '2',
    title: 'AI & Machine Learning',
    instructor: 'Dr. Emma Davis',
    students: 0,
    status: 'draft',
    createdAt: new Date('2024-12-01'),
  },
  {
    id: 'course_5',
    tenantId: '3',
    title: 'Digital Art Fundamentals',
    instructor: 'Alex Rivera',
    students: 125,
    status: 'flagged',
    createdAt: new Date('2024-10-20'),
  },
]

export const mockRevenueData: ChartData[] = [
  { name: 'Jan', value: 12500, recurring: 9500, onetime: 3000 },
  { name: 'Feb', value: 15200, recurring: 11200, onetime: 4000 },
  { name: 'Mar', value: 18900, recurring: 13500, onetime: 5400 },
  { name: 'Apr', value: 16700, recurring: 12000, onetime: 4700 },
  { name: 'May', value: 22400, recurring: 16000, onetime: 6400 },
  { name: 'Jun', value: 28600, recurring: 20000, onetime: 8600 },
  { name: 'Jul', value: 32100, recurring: 22500, onetime: 9600 },
  { name: 'Aug', value: 35800, recurring: 24800, onetime: 11000 },
  { name: 'Sep', value: 38500, recurring: 27000, onetime: 11500 },
  { name: 'Oct', value: 42300, recurring: 29800, onetime: 12500 },
  { name: 'Nov', value: 45600, recurring: 31500, onetime: 14100 },
  { name: 'Dec', value: 52300, recurring: 36000, onetime: 16300 },
]

export const mockTenantGrowthData: ChartData[] = [
  { name: 'Week 1', new: 2, churned: 0, total: 2 },
  { name: 'Week 2', new: 3, churned: 0, total: 5 },
  { name: 'Week 3', new: 1, churned: 1, total: 5 },
  { name: 'Week 4', new: 4, churned: 0, total: 9 },
  { name: 'Week 5', new: 2, churned: 1, total: 10 },
  { name: 'Week 6', new: 3, churned: 0, total: 13 },
  { name: 'Week 7', new: 5, churned: 1, total: 17 },
  { name: 'Week 8', new: 2, churned: 0, total: 19 },
]

export const mockStudentDistribution: ChartData[] = [
  { name: 'K-12', value: 8500 },
  { name: 'Higher Ed', value: 6200 },
  { name: 'Professional Dev', value: 3400 },
  { name: 'Corporate Training', value: 2100 },
]

export const mockTopTenantsData: ChartData[] = [
  { name: 'Global Learning Hub', value: 5600 },
  { name: 'Lincoln High School', value: 2400 },
  { name: 'University Online', value: 3200 },
  { name: 'Tech Academy', value: 1200 },
  { name: 'Creative Institute', value: 450 },
]
