import {
  StudentCourse,
  StudentModule,
  StudentLesson,
  StudentAssignment,
  StudentQuiz,
  StudentGrade,
  DiscussionThread,
  CourseAnnouncement,
  ScheduleEvent,
  StudentMessage,
  StudentMaterial,
  StudentProgress,
} from "./student-types";

export const STUDENT_COURSES: StudentCourse[] = [
  {
    id: "cs101",
    name: "Introduction to Computer Science",
    code: "CS101",
    instructor: "Dr. Sarah Johnson",
    thumbnail: "/placeholder.svg?height=200&width=300",
    credits: 3,
    enrollment_date: "2024-01-15",
    status: "active",
    progress: 65,
    grade: "A-",
    gpa: 3.7,
    due_assignments: 2,
    unread_announcements: 3,
    instructor_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
  },
  {
    id: "math201",
    name: "Calculus II",
    code: "MATH201",
    instructor: "Prof. Michael Chen",
    thumbnail: "/placeholder.svg?height=200&width=300",
    credits: 4,
    enrollment_date: "2024-01-15",
    status: "active",
    progress: 72,
    grade: "B+",
    gpa: 3.5,
    due_assignments: 1,
    unread_announcements: 1,
    instructor_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael",
  },
  {
    id: "eng102",
    name: "English Literature",
    code: "ENG102",
    instructor: "Dr. Emma Wilson",
    thumbnail: "/placeholder.svg?height=200&width=300",
    credits: 3,
    enrollment_date: "2024-01-15",
    status: "active",
    progress: 58,
    grade: "B",
    gpa: 3.0,
    due_assignments: 3,
    unread_announcements: 2,
    instructor_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emma",
  },
];

export const STUDENT_MODULES: StudentModule[] = [
  {
    id: "mod1",
    course_id: "cs101",
    title: "Getting Started with Basics",
    week_number: 1,
    description: "Introduction to the course and basic concepts",
    order: 1,
  },
  {
    id: "mod2",
    course_id: "cs101",
    title: "Programming Fundamentals",
    week_number: 2,
    description: "Deep dive into logic and flow control",
    order: 2,
  },
  {
    id: "mod3",
    course_id: "math201",
    title: "Limits and Continuity",
    week_number: 1,
    description: "Review of limits and introduction to continuity",
    order: 1,
  },
  {
    id: "mod4",
    course_id: "math201",
    title: "Techniques of Integration",
    week_number: 2,
    description: "Integration by parts, substitution, and partial fractions",
    order: 2,
  },
  {
    id: "mod5",
    course_id: "eng102",
    title: "The Romantics",
    week_number: 1,
    description: "Poetry and prose of the Romantic period",
    order: 1,
  },
  {
    id: "mod6",
    course_id: "eng102",
    title: "Victorian Literature",
    week_number: 2,
    description: "Novels and social commentary of the Victorian era",
    order: 2,
  },
];

export const STUDENT_LESSONS: StudentLesson[] = [
  // CS101 Lessons
  {
    id: "lesson1",
    course_id: "cs101",
    module_id: "mod1",
    title: "Introduction to Programming",
    description: "Learn the basics of programming and variables",
    type: "video",
    duration: 45,
    is_locked: false,
    completed: true,
    completed_at: "2024-02-01",
    order: 1,
    video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: "lesson2",
    course_id: "cs101",
    module_id: "mod1",
    title: "Data Types and Operations",
    description: "Understand different data types",
    type: "video",
    duration: 38,
    is_locked: false,
    completed: true,
    completed_at: "2024-02-03",
    order: 2,
    video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: "lesson3",
    course_id: "cs101",
    module_id: "mod2",
    title: "Control Flow Basics",
    description: "Master if, else, and loops",
    type: "document",
    duration: 20,
    is_locked: false,
    completed: true,
    completed_at: "2024-02-05",
    order: 3,
  },
  {
    id: "lesson4",
    course_id: "cs101",
    module_id: "mod2",
    title: "Functions and Scope",
    description: "Learn about functions and variable scope",
    type: "video",
    duration: 52,
    is_locked: false,
    completed: false,
    completed_at: null,
    order: 4,
    video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: "lesson5",
    course_id: "cs101",
    module_id: "mod2",
    title: "Arrays and Lists",
    description: "Work with collections of data",
    type: "video",
    duration: 48,
    is_locked: true,
    completed: false,
    completed_at: null,
    order: 5,
    video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  // MATH201 Lessons
  {
    id: "lesson6",
    course_id: "math201",
    module_id: "mod3",
    title: "Review of Limits",
    description: "Quick review of limit concepts from Calculus I",
    type: "video",
    duration: 35,
    is_locked: false,
    completed: true,
    completed_at: "2024-02-01",
    order: 1,
    video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: "lesson7",
    course_id: "math201",
    module_id: "mod3",
    title: "Continuity and Differentiability",
    description: "Understanding continuous functions and their properties",
    type: "video",
    duration: 42,
    is_locked: false,
    completed: true,
    completed_at: "2024-02-03",
    order: 2,
    video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: "lesson8",
    course_id: "math201",
    module_id: "mod3",
    title: "Squeeze Theorem Applications",
    description: "Solving complex limits with the Squeeze Theorem",
    type: "document",
    duration: 25,
    is_locked: false,
    completed: true,
    completed_at: "2024-02-05",
    order: 3,
  },
  {
    id: "lesson9",
    course_id: "math201",
    module_id: "mod4",
    title: "Integration by Parts",
    description: "Master the integration by parts technique",
    type: "video",
    duration: 50,
    is_locked: false,
    completed: true,
    completed_at: "2024-02-07",
    order: 4,
    video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: "lesson10",
    course_id: "math201",
    module_id: "mod4",
    title: "Trigonometric Substitution",
    description: "Using trig identities to evaluate integrals",
    type: "video",
    duration: 55,
    is_locked: false,
    completed: false,
    completed_at: null,
    order: 5,
    video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: "lesson11",
    course_id: "math201",
    module_id: "mod4",
    title: "Partial Fractions",
    description: "Decomposing rational expressions for integration",
    type: "video",
    duration: 45,
    is_locked: true,
    completed: false,
    completed_at: null,
    order: 6,
    video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  // ENG102 Lessons
  {
    id: "lesson12",
    course_id: "eng102",
    module_id: "mod5",
    title: "Introduction to Romanticism",
    description: "Historical context and key themes of the Romantic movement",
    type: "video",
    duration: 40,
    is_locked: false,
    completed: true,
    completed_at: "2024-02-01",
    order: 1,
    video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: "lesson13",
    course_id: "eng102",
    module_id: "mod5",
    title: "Wordsworth and Nature Poetry",
    description: "Analyzing Wordsworth's major works and nature imagery",
    type: "video",
    duration: 38,
    is_locked: false,
    completed: true,
    completed_at: "2024-02-03",
    order: 2,
    video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: "lesson14",
    course_id: "eng102",
    module_id: "mod5",
    title: "Byron, Shelley, and Keats",
    description: "Comparing the second generation of Romantic poets",
    type: "document",
    duration: 30,
    is_locked: false,
    completed: false,
    completed_at: null,
    order: 3,
  },
  {
    id: "lesson15",
    course_id: "eng102",
    module_id: "mod6",
    title: "Charles Dickens and Social Reform",
    description: "How Dickens used fiction to address Victorian social issues",
    type: "video",
    duration: 48,
    is_locked: false,
    completed: false,
    completed_at: null,
    order: 4,
    video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: "lesson16",
    course_id: "eng102",
    module_id: "mod6",
    title: "The Brontë Sisters",
    description: "Exploring Wuthering Heights and Jane Eyre",
    type: "video",
    duration: 52,
    is_locked: true,
    completed: false,
    completed_at: null,
    order: 5,
    video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
];

export const STUDENT_ASSIGNMENTS: StudentAssignment[] = [
  {
    id: "assign1",
    course_id: "cs101",
    category: "module",
    target_name: "Programming Fundamentals",
    title: "Variables and Operators",
    description: "Create a program that demonstrates the use of variables, arithmetic operators, and basic input/output. Your program should calculate the area and perimeter of a rectangle given user input.",
    due_date: "2024-02-08T23:59:00",
    status: "graded",
    submission_date: "2024-02-07T14:30:00",
    grade: 95,
    feedback: "Excellent work! Clean code and well-commented. Great use of descriptive variable names.",
    points_earned: 95,
    total_points: 100,
    has_attachment: true,
  },
  {
    id: "assign2",
    course_id: "cs101",
    category: "module",
    target_name: "Getting Started with Basics",
    title: "Control Flow Assignment",
    description: "Implement a grade calculator using if/else conditionals and a loop to process multiple students. Handle edge cases such as invalid grades gracefully.",
    due_date: "2024-02-15T23:59:00",
    status: "submitted",
    submission_date: "2024-02-14T20:10:00",
    grade: null,
    feedback: null,
    points_earned: null,
    total_points: 100,
    has_attachment: false,
  },
  {
    id: "assign3",
    course_id: "math201",
    category: "course",
    target_name: "Calculus II",
    title: "Calculus Problem Set 1",
    description: "Solve 30 problems covering limits, continuity, and basic derivatives. Show all working. Problems are in the attached PDF. Submit your solutions as a single PDF file.",
    due_date: "2024-02-12T23:59:00",
    status: "pending",
    submission_date: null,
    grade: null,
    feedback: null,
    points_earned: null,
    total_points: 100,
    has_attachment: true,
  },
  {
    id: "assign4",
    course_id: "eng102",
    category: "lesson",
    target_name: "Byron, Shelley, and Keats",
    title: "Romantic Poetry Essay",
    description: "Write a 1500-word analytical essay comparing the use of nature imagery in poems by at least two of the second-generation Romantic poets. Include citations from the primary texts.",
    due_date: "2024-02-10T23:59:00",
    status: "late",
    submission_date: "2024-02-11T09:15:00",
    grade: 85,
    feedback: "Good analysis but submitted late. -5 points penalty applied. The comparison between Keats and Shelley was particularly insightful.",
    points_earned: 85,
    total_points: 100,
    has_attachment: false,
  },
  {
    id: "assign5",
    course_id: "cs101",
    category: "lesson",
    target_name: "Introduction to Python",
    title: "Python Function Design",
    description: "Design and implement a library of 5 utility functions demonstrating use of default arguments, *args, and **kwargs. Document each function with docstrings.",
    due_date: "2024-02-22T23:59:00",
    status: "pending",
    submission_date: null,
    grade: null,
    feedback: null,
    points_earned: null,
    total_points: 75,
    has_attachment: true,
  },
  {
    id: "assign6",
    course_id: "math201",
    category: "module",
    target_name: "Techniques of Integration",
    title: "Integration Techniques Worksheet",
    description: "Complete the worksheet covering integration by parts, trigonometric substitution, and partial fractions. All 20 problems must be solved with full working shown.",
    due_date: "2024-03-01T23:59:00",
    status: "missing",
    submission_date: null,
    grade: null,
    feedback: null,
    points_earned: null,
    total_points: 50,
    has_attachment: true,
  },
];

export const STUDENT_QUIZZES: StudentQuiz[] = [
  {
    id: "quiz1",
    course_id: "cs101",
    title: "Variables Quiz",
    category: "lesson",
    target_name: "Lesson: Data Types and Operations",
    type: "graded",
    total_questions: 3,
    time_limit: 15,
    attempts_allowed: 2,
    status: "submitted",
    attempts: [
      {
        attempt_number: 1,
        score: 85,
        date_attempted: "2024-02-02",
      },
    ],
    best_score: 85,
    questions: [
      {
        id: "q1",
        text: "Which of the following is NOT a primitive data type in typical programming languages?",
        options: ["Integer", "String", "Object/Class", "Boolean"],
        correct_option_index: 2,
        points: 5
      },
      {
        id: "q2",
        text: "What happens when you reassign a constant variable?",
        options: ["It updates successfully", "It throws a runtime error", "It is ignored silently", "It creates a new memory reference"],
        correct_option_index: 1,
        points: 5
      },
      {
        id: "q3",
        text: "Which operator is used to check strictly for equality in JavaScript?",
        options: ["=", "==", "===", "!="],
        correct_option_index: 2,
        points: 5
      }
    ]
  },
  {
    id: "quiz2",
    course_id: "cs101",
    title: "Control Flow Practice",
    category: "module",
    target_name: "Module: Programming Fundamentals",
    type: "practice",
    total_questions: 3,
    time_limit: 10,
    attempts_allowed: 5,
    status: "in_progress",
    attempts: [],
    best_score: null,
    questions: [
      {
        id: "q4",
        text: "Which loop guarantees execution at least once?",
        options: ["for loop", "while loop", "do-while loop", "foreach loop"],
        correct_option_index: 2,
        points: 10
      },
      {
        id: "q5",
        text: "What does a 'break' statement do inside a loop?",
        options: ["Exits the loop entirely", "Skips to the next iteration", "Pauses execution", "Restarts the loop"],
        correct_option_index: 0,
        points: 10
      },
      {
        id: "q6",
        text: "An `if` statement evaluates its condition to a:",
        options: ["String", "Function", "Boolean", "Number"],
        correct_option_index: 2,
        points: 10
      }
    ]
  },
  {
    id: "quiz3",
    course_id: "math201",
    title: "Derivatives Practice",
    category: "course",
    target_name: "Course: Calculus II",
    type: "ungraded",
    total_questions: 3,
    time_limit: 30,
    attempts_allowed: 3,
    status: "not_started",
    attempts: [],
    best_score: null,
    questions: [
      {
        id: "q7",
        text: "What is the derivative of x^2?",
        options: ["x", "2x", "x^3 / 3", "2x^2"],
        correct_option_index: 1,
        points: 1
      },
      {
        id: "q8",
        text: "The derivative of sin(x) is:",
        options: ["cos(x)", "-cos(x)", "-sin(x)", "tan(x)"],
        correct_option_index: 0,
        points: 1
      },
      {
        id: "q9",
        text: "What rule do you use to differentiate f(g(x))?",
        options: ["Product Rule", "Quotient Rule", "Chain Rule", "Power Rule"],
        correct_option_index: 2,
        points: 1
      }
    ]
  },
];

export const STUDENT_GRADES: StudentGrade[] = [
  {
    course_id: "cs101",
    course_name: "Introduction to Computer Science",
    assignments: { earned: 46, total: 50, weight: 35 },
    tests: { earned: 87, total: 100, weight: 40 },
    quizzes: { earned: 26, total: 30, weight: 15 },
    forum_activities: { earned: 9, total: 10, weight: 10 },
    final_points: 168,
    total_points: 190,
    final_grade: 90.5,
    letter_grade: "A-",
  },
  {
    course_id: "math201",
    course_name: "Calculus II",
    assignments: { earned: 38, total: 50, weight: 35 },
    tests: { earned: 79, total: 100, weight: 40 },
    quizzes: { earned: 23, total: 30, weight: 15 },
    forum_activities: { earned: 7, total: 10, weight: 10 },
    final_points: 147,
    total_points: 190,
    final_grade: 84.2,
    letter_grade: "B+",
  },
  {
    course_id: "eng102",
    course_name: "English Literature",
    assignments: { earned: 36, total: 50, weight: 35 },
    tests: { earned: 74, total: 100, weight: 40 },
    quizzes: { earned: 22, total: 30, weight: 15 },
    forum_activities: { earned: 8, total: 10, weight: 10 },
    final_points: 140,
    total_points: 190,
    final_grade: 80.5,
    letter_grade: "B",
  },
];

export const DISCUSSION_THREADS: DiscussionThread[] = [
  // ── General Forum ──────────────────────────────────────────────
  {
    id: "gen1",
    course_id: null,
    forum_type: "general",
    title: "Best study techniques for online learning?",
    description: "I've been struggling to stay focused during online lectures. What study techniques have worked best for you? I've tried the Pomodoro method but I find it hard to stay on track.",
    author: "John Doe",
    author_id: "student_current",
    author_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
    created_at: "2024-02-06T10:00:00",
    replies_count: 5,
    views: 82,
    is_pinned: false,
    has_unread: true,
    comments: [
      {
        id: "c1",
        thread_id: "gen1",
        author: "Jane Smith",
        author_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
        content: "I use the Feynman Technique — try explaining what you learned as if teaching someone else. Really helps solidify concepts!",
        created_at: "2024-02-06T11:30:00",
        is_helpful: true,
        likes: 7,
        replies: [
          {
            id: "r1",
            comment_id: "c1",
            author: "Mike Chen",
            author_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mike",
            content: "Great tip! I second this. Teaching it back is way more effective than re-reading notes.",
            created_at: "2024-02-06T12:00:00",
            likes: 3,
          }
        ],
      },
      {
        id: "c2",
        thread_id: "gen1",
        author: "Aisha Bello",
        author_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Aisha",
        content: "I schedule dedicated study blocks in Google Calendar. Treating it like a class you can't skip really changes the mindset.",
        created_at: "2024-02-06T13:00:00",
        likes: 4,
        replies: [],
      },
    ],
  },
  {
    id: "gen2",
    course_id: null,
    forum_type: "general",
    title: "Tips for managing multiple deadlines?",
    description: "I have 3 assignments due next week and two quizzes. How do you all manage overlapping deadlines without burning out? Looking for practical advice!",
    author: "Carlos Rivera",
    author_id: "carlos_r",
    author_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos",
    created_at: "2024-02-05T09:00:00",
    replies_count: 3,
    views: 54,
    is_pinned: true,
    has_unread: false,
    comments: [
      {
        id: "c3",
        thread_id: "gen2",
        author: "Priya Nair",
        author_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Priya",
        content: "I use the Eisenhower matrix — split tasks into urgent/important quadrants. Helps me decide what to work on first without panic.",
        created_at: "2024-02-05T10:15:00",
        is_helpful: true,
        likes: 9,
        replies: [],
      }
    ],
  },
  {
    id: "gen3",
    course_id: null,
    forum_type: "general",
    title: "Introductions — who is everyone?",
    description: "Let's get to know each other! Share your name, what you're studying, and one fun fact about yourself. I'll start — I'm John, studying CS, and I can solve a Rubik's cube in under 2 minutes!",
    author: "Admin",
    author_id: "admin",
    author_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Admin",
    created_at: "2024-01-15T08:00:00",
    replies_count: 14,
    views: 210,
    is_pinned: true,
    has_unread: false,
    comments: [],
  },
  // ── Course Forums ───────────────────────────────────────────────
  {
    id: "cs1",
    course_id: "cs101",
    forum_type: "course",
    title: "How to debug for loop issues in Python?",
    description: "Hey everyone, I'm working through module 2 and running into trouble with nested for loops. My code seems to produce unexpected results — has anyone run into this? Here's my code snippet...",
    author: "John Doe",
    author_id: "student_current",
    author_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
    created_at: "2024-02-06T14:00:00",
    replies_count: 12,
    views: 45,
    is_pinned: false,
    has_unread: true,
    comments: [
      {
        id: "c4",
        thread_id: "cs1",
        author: "Jane Smith",
        author_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
        content: "I had the same issue! Adjusting the termination condition fixed it. Check if your index is off by one — change `<= array.length` to `< array.length`.",
        created_at: "2024-02-06T15:20:00",
        is_helpful: true,
        likes: 4,
        replies: [],
      },
      {
        id: "c5",
        thread_id: "cs1",
        author: "Dr. Sarah Johnson",
        author_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
        is_instructor: true,
        content: "Excellent suggestion. Typically for-loop issues stem from accessing array elements outside bounds. Use the debugger to step through each iteration carefully.",
        created_at: "2024-02-06T16:45:00",
        is_helpful: true,
        likes: 8,
        replies: [
          {
            id: "r2",
            comment_id: "c5",
            author: "John Doe",
            author_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
            content: "Thanks Dr. Johnson! The debugger really helped — I was indeed accessing out of bounds. Fixed it!",
            created_at: "2024-02-06T18:30:00",
            likes: 2,
          }
        ],
      },
    ],
  },
  {
    id: "cs2",
    course_id: "cs101",
    forum_type: "course",
    title: "Assignment 2 clarification needed",
    description: "Can someone clarify what format the Assignment 2 submission should be in? The instructions mention PDF and ZIP but I'm not sure which to use for the code portion.",
    author: "Dr. Sarah Johnson",
    author_id: "instructor_sarah",
    author_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    created_at: "2024-02-05T11:00:00",
    replies_count: 28,
    views: 102,
    is_pinned: true,
    has_unread: false,
    comments: [],
  },
  {
    id: "math1",
    course_id: "math201",
    forum_type: "course",
    title: "Integration by parts — worked examples?",
    description: "I'm struggling with integration by parts, particularly when to use it vs substitution. Can anyone share some worked examples or point me to good resources?",
    author: "Jane Smith",
    author_id: "jane_s",
    author_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
    created_at: "2024-02-04T09:30:00",
    replies_count: 5,
    views: 23,
    is_pinned: false,
    has_unread: true,
    comments: [],
  },
];

export const COURSE_ANNOUNCEMENTS: CourseAnnouncement[] = [
  // ── General Announcements ──────────────────────────────────────────
  {
    id: "gen_ann1",
    announcement_type: "general",
    course_id: null,
    title: "Platform Maintenance Scheduled — Saturday 12th Feb, 2 AM",
    content: "Our platform will undergo scheduled maintenance on Saturday 12th February from 2:00 AM to 5:00 AM (GMT+1). During this window, the platform will be unavailable. Please plan your study sessions accordingly. We apologize for any inconvenience and appreciate your patience.",
    instructor: "FnSkills Admin",
    instructor_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Admin",
    created_at: "2024-02-07T09:00:00",
    is_read: false,
    priority: "important",
  },
  {
    id: "gen_ann2",
    announcement_type: "general",
    course_id: null,
    title: "New Feature: Dark Mode & Improved Mobile Experience",
    content: "We're excited to announce two major updates to the FnSkills platform. Dark mode is now available — toggle it in your profile settings. We've also significantly improved the mobile experience, making it easier to access your courses, assignments, and quizzes on the go.",
    instructor: "FnSkills Product Team",
    instructor_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Product",
    created_at: "2024-02-03T10:00:00",
    is_read: true,
    priority: "normal",
  },
  {
    id: "gen_ann3",
    announcement_type: "general",
    course_id: null,
    title: "End-of-Semester Deadlines Reminder",
    content: "A reminder that all outstanding assignments and quizzes must be submitted by the end of the semester. Late submissions will no longer be accepted after the final deadline. Please check your course pages for specific cut-off times. If you have extenuating circumstances, contact your instructor as soon as possible.",
    instructor: "Academic Registry",
    instructor_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Registry",
    created_at: "2024-02-01T08:00:00",
    is_read: true,
    priority: "urgent",
  },
  // ── Course Announcements ──────────────────────────────────────────
  {
    id: "announce1",
    announcement_type: "course",
    course_id: "cs101",
    title: "Assignment 2 Due Date Extended",
    content: "Following several student requests and a technical issue with the submission portal last night, the deadline for Assignment 2 has been extended to February 15th at 11:59 PM. Please use this extra time to review your work carefully. The grading rubric has also been updated — please check the Materials section.",
    instructor: "Dr. Sarah Johnson",
    instructor_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    created_at: "2024-02-06T14:00:00",
    is_read: false,
    priority: "important",
  },
  {
    id: "announce2",
    announcement_type: "course",
    course_id: "cs101",
    title: "Midterm Exam — Scheduled for March 1st",
    content: "The CS101 midterm examination is confirmed for March 1st, held in Lecture Hall B from 10:00 AM to 12:00 PM. The exam will cover chapters 1 through 5, including all lab exercises. A revision guide has been uploaded to the Materials section. Office hours will be extended in the week leading up to the exam.",
    instructor: "Dr. Sarah Johnson",
    instructor_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    created_at: "2024-02-05T09:30:00",
    is_read: true,
    priority: "normal",
  },
  {
    id: "announce3",
    announcement_type: "course",
    course_id: "math201",
    title: "Office Hours This Friday — Room 305",
    content: "I will be holding additional office hours this Friday from 2:00 PM to 4:00 PM in Room 305, Building C. This is an open session — bring any questions about integration techniques, the upcoming problem set, or anything covered in lectures. No appointment needed.",
    instructor: "Prof. Michael Chen",
    instructor_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael",
    created_at: "2024-02-05T08:00:00",
    is_read: true,
    priority: "normal",
  },
  {
    id: "announce4",
    announcement_type: "course",
    course_id: "eng102",
    title: "Essay Submission Guidelines Update",
    content: "Please note a change to the essay submission format. All essays must now be submitted as a single PDF file with font size 12, double-spaced, and with 1-inch margins. Submissions that do not follow this format will be returned for resubmission. The deadline remains February 10th at 11:59 PM.",
    instructor: "Dr. Emily Brooks",
    instructor_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emily",
    created_at: "2024-02-04T11:00:00",
    is_read: false,
    priority: "important",
  },
];

export const SCHEDULE_EVENTS: ScheduleEvent[] = [
  {
    id: "event1",
    title: "CS101 Lecture",
    course_id: "cs101",
    course_name: "CS101",
    type: "class",
    start_time: "2024-02-08T10:00:00",
    end_time: "2024-02-08T11:30:00",
    location: "Building A, Room 101",
    description: "Regular lecture session",
  },
  {
    id: "event2",
    title: "Math201 Assignment Due",
    course_id: "math201",
    course_name: "MATH201",
    type: "assignment_due",
    start_time: "2024-02-12T23:59:00",
    end_time: "2024-02-12T23:59:00",
    location: null,
    description: "Calculus Problem Set due by midnight",
  },
  {
    id: "event3",
    title: "Quiz 2: Control Flow",
    course_id: "cs101",
    course_name: "CS101",
    type: "quiz",
    start_time: "2024-02-10T14:00:00",
    end_time: "2024-02-10T14:30:00",
    location: "Online",
    description: "Timed quiz on control flow concepts",
  },
  {
    id: "event4",
    title: "Office Hours",
    course_id: "cs101",
    course_name: "CS101",
    type: "office_hours",
    start_time: "2024-02-09T15:00:00",
    end_time: "2024-02-09T16:30:00",
    location: "Room 205",
    description: "Optional office hours with instructor",
  },
];

export const STUDENT_MESSAGES: StudentMessage[] = [
  {
    id: "msg1",
    sender_id: "instr1",
    sender_name: "Dr. Sarah Johnson",
    sender_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    content: "Great work on Assignment 1! Your code was clean and well-structured.",
    timestamp: "2024-02-06T14:30:00",
    is_read: true,
    conversation_id: "conv1",
  },
  {
    id: "msg2",
    sender_id: "instr1",
    sender_name: "Dr. Sarah Johnson",
    sender_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    content: "I've also posted some extra resources for the next module. Check them out!",
    timestamp: "2024-02-07T09:15:00",
    is_read: true,
    conversation_id: "conv1",
  },
  {
    id: "msg3",
    sender_id: "peer1",
    sender_name: "John Doe",
    sender_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
    content: "Did you understand the for loop explanation in the recent lecture?",
    timestamp: "2024-02-06T10:15:00",
    is_read: false,
    conversation_id: "conv2",
  },
  {
    id: "msg4",
    sender_id: "peer2",
    sender_name: "Jane Smith",
    sender_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
    content: "Hey, are we still meeting for the study group today?",
    timestamp: "2024-02-08T11:00:00",
    is_read: false,
    conversation_id: "conv3",
  },
  {
    id: "msg5",
    sender_id: "instr2",
    sender_name: "Prof. Michael Chen",
    sender_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael",
    content: "The grading for the midterm is almost complete. Expect results by Friday.",
    timestamp: "2024-02-05T16:45:00",
    is_read: true,
    conversation_id: "conv4",
  },
  {
    id: "msg6",
    sender_id: "peer3",
    sender_name: "Alice Wang",
    sender_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alice",
    content: "Can you share the link to the shared document? I lost it.",
    timestamp: "2024-02-08T08:30:00",
    is_read: false,
    conversation_id: "conv5",
  },
];

export const STUDENT_MATERIALS: StudentMaterial[] = [
  // ── CS101 — Module 1: Getting Started with Basics ──────────────────
  {
    id: "mat_cs1_m1_1",
    course_id: "cs101",
    module_id: "mod1",
    name: "Lecture Slides — Week 1",
    description: "Introduction to computing concepts, hardware overview, and course structure.",
    type: "pdf",
    size: "3.1 MB",
    uploaded_by: "Dr. Sarah Johnson",
    uploaded_date: "2024-01-29",
    download_count: 58,
  },
  {
    id: "mat_cs1_m1_2",
    course_id: "cs101",
    module_id: "mod1",
    name: "Lab Exercise 1 — Setup Guide",
    description: "Step-by-step instructions to install Python and configure your development environment.",
    type: "pdf",
    size: "1.4 MB",
    uploaded_by: "Dr. Sarah Johnson",
    uploaded_date: "2024-01-30",
    download_count: 52,
  },
  {
    id: "mat_cs1_m1_3",
    course_id: "cs101",
    module_id: "mod1",
    name: "Starter Code Examples",
    description: "ZIP archive of all sample programs covered in Week 1 lectures.",
    type: "zip",
    size: "2.8 MB",
    uploaded_by: "Dr. Sarah Johnson",
    uploaded_date: "2024-01-31",
    download_count: 45,
  },
  // ── CS101 — Module 2: Programming Fundamentals ─────────────────────
  {
    id: "mat_cs1_m2_1",
    course_id: "cs101",
    module_id: "mod2",
    name: "Lecture Notes — Control Flow & Loops",
    description: "Comprehensive notes on if/else, for loops, while loops, and break/continue.",
    type: "pdf",
    size: "4.2 MB",
    uploaded_by: "Dr. Sarah Johnson",
    uploaded_date: "2024-02-01",
    download_count: 47,
  },
  {
    id: "mat_cs1_m2_2",
    course_id: "cs101",
    module_id: "mod2",
    name: "Programming Examples — Functions",
    description: "Code samples for functions with default arguments, *args, and **kwargs.",
    type: "zip",
    size: "15.2 MB",
    uploaded_by: "Dr. Sarah Johnson",
    uploaded_date: "2024-02-03",
    download_count: 38,
  },
  {
    id: "mat_cs1_m2_3",
    course_id: "cs101",
    module_id: "mod2",
    name: "Debugging Cheatsheet",
    description: "Quick reference card for common Python errors and how to fix them.",
    type: "pdf",
    size: "0.8 MB",
    uploaded_by: "Dr. Sarah Johnson",
    uploaded_date: "2024-02-05",
    download_count: 71,
  },
  // ── MATH201 — Module 3: Limits and Continuity ──────────────────────
  {
    id: "mat_ma_m3_1",
    course_id: "math201",
    module_id: "mod3",
    name: "Calculus Textbook — Chapter 3",
    description: "Limits, continuity theorems, and the Squeeze theorem with worked examples.",
    type: "pdf",
    size: "5.1 MB",
    uploaded_by: "Prof. Michael Chen",
    uploaded_date: "2024-02-02",
    download_count: 61,
  },
  {
    id: "mat_ma_m3_2",
    course_id: "math201",
    module_id: "mod3",
    name: "Limits Practice Problems",
    description: "30 graded practice problems on evaluating limits and identifying discontinuities.",
    type: "pdf",
    size: "1.9 MB",
    uploaded_by: "Prof. Michael Chen",
    uploaded_date: "2024-02-03",
    download_count: 49,
  },
  {
    id: "mat_ma_m3_3",
    course_id: "math201",
    module_id: "mod3",
    name: "Continuity Concept Map",
    description: "Visual diagram summarising types of discontinuity and their properties.",
    type: "image",
    size: "0.6 MB",
    uploaded_by: "Prof. Michael Chen",
    uploaded_date: "2024-02-04",
    download_count: 28,
  },
  // ── MATH201 — Module 4: Techniques of Integration ──────────────────
  {
    id: "mat_ma_m4_1",
    course_id: "math201",
    module_id: "mod4",
    name: "Integration Techniques — Lecture Slides",
    description: "Slides covering integration by parts, trig substitution, and partial fractions.",
    type: "pdf",
    size: "6.3 MB",
    uploaded_by: "Prof. Michael Chen",
    uploaded_date: "2024-02-07",
    download_count: 55,
  },
  {
    id: "mat_ma_m4_2",
    course_id: "math201",
    module_id: "mod4",
    name: "Integration Worksheet — 20 Problems",
    description: "Worksheet for the graded module assignment. Show all working.",
    type: "pdf",
    size: "2.2 MB",
    uploaded_by: "Prof. Michael Chen",
    uploaded_date: "2024-02-08",
    download_count: 44,
  },
  // ── ENG102 — Module 5: The Romantics ──────────────────────────────
  {
    id: "mat_en_m5_1",
    course_id: "eng102",
    module_id: "mod5",
    name: "Romanticism — Historical Context Guide",
    description: "Overview of the Romantic movement: historical background, key themes, and major poets.",
    type: "pdf",
    size: "3.7 MB",
    uploaded_by: "Dr. Emily Brooks",
    uploaded_date: "2024-02-01",
    download_count: 39,
  },
  {
    id: "mat_en_m5_2",
    course_id: "eng102",
    module_id: "mod5",
    name: "Selected Poems — Wordsworth, Keats, Shelley",
    description: "PDF anthology of primary texts used in Week 1 seminars.",
    type: "pdf",
    size: "4.5 MB",
    uploaded_by: "Dr. Emily Brooks",
    uploaded_date: "2024-02-02",
    download_count: 51,
  },
  {
    id: "mat_en_m5_3",
    course_id: "eng102",
    module_id: "mod5",
    name: "Essay Writing Framework",
    description: "Guide to structuring literary analysis essays: thesis, evidence, commentary.",
    type: "document",
    size: "0.9 MB",
    uploaded_by: "Dr. Emily Brooks",
    uploaded_date: "2024-02-03",
    download_count: 66,
  },
  // ── ENG102 — Module 6: Victorian Literature ────────────────────────
  {
    id: "mat_en_m6_1",
    course_id: "eng102",
    module_id: "mod6",
    name: "Victorian Literature — Lecture Notes",
    description: "Notes on Dickens, the Brontës, and the social reform context of Victorian fiction.",
    type: "pdf",
    size: "5.0 MB",
    uploaded_by: "Dr. Emily Brooks",
    uploaded_date: "2024-02-06",
    download_count: 33,
  },
  {
    id: "mat_en_m6_2",
    course_id: "eng102",
    module_id: "mod6",
    name: "Wuthering Heights — Annotated Extract",
    description: "Annotated passage from Chapter 9 with discussion points for seminar.",
    type: "pdf",
    size: "1.1 MB",
    uploaded_by: "Dr. Emily Brooks",
    uploaded_date: "2024-02-07",
    download_count: 24,
  },
];

export const STUDENT_PROGRESS: StudentProgress[] = [
  {
    course_id: "cs101",
    course_name: "Introduction to Computer Science",
    lessons_completed: 3,
    total_lessons: 8,
    assignments_completed: 1,
    total_assignments: 5,
    quizzes_taken: 1,
    total_quizzes: 4,
    overall_progress: 62,
    last_activity: "2024-02-06T14:30:00",
  },
  {
    course_id: "math201",
    course_name: "Calculus II",
    lessons_completed: 4,
    total_lessons: 10,
    assignments_completed: 2,
    total_assignments: 6,
    quizzes_taken: 0,
    total_quizzes: 5,
    overall_progress: 55,
    last_activity: "2024-02-05T10:00:00",
  },
  {
    course_id: "eng102",
    course_name: "English Literature",
    lessons_completed: 2,
    total_lessons: 6,
    assignments_completed: 1,
    total_assignments: 4,
    quizzes_taken: 1,
    total_quizzes: 3,
    overall_progress: 45,
    last_activity: "2024-02-04T16:20:00",
  },
];

// ── Live Classes Mock Data ──────────────────────────────────────────────────
const _now = new Date();
const _d = (daysOffset: number, hour: number) => {
  const d = new Date(_now);
  d.setDate(d.getDate() + daysOffset);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
};

export type MeetingStatus = "upcoming" | "live" | "ended";
export type AttendanceStatus = "pending" | "present" | "absent" | "partial";

export interface StudentMeeting {
  id: string;
  name: string;
  description: string;
  creator: { id: string; name: string; avatar_url: string };
  start_time: string;
  duration: number; // minutes
  status: MeetingStatus;
  zoom: { meeting_id: string; password: string };
  attendance: {
    status: AttendanceStatus;
    minutes_present: number;
    percentage: number;
    threshold_minutes: number;
  };
}

export const STUDENT_MOCK_MEETINGS: StudentMeeting[] = [
  {
    id: "m1",
    name: "Introduction to React Hooks",
    description: "A hands-on session covering useState, useEffect, and custom hooks. We will build a small project together and explore common hook patterns used in production apps.",
    creator: { id: "3", name: "Dr. Sarah Johnson", avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah" },
    start_time: _now.toISOString(),
    duration: 60,
    status: "live",
    zoom: { meeting_id: "84123456789", password: "abc123" },
    attendance: { status: "pending", minutes_present: 0, percentage: 0, threshold_minutes: 48 },
  },
  {
    id: "m2",
    name: "Advanced CSS Animations",
    description: "Deep dive into keyframes, transitions, and the Web Animations API. Bring your creativity — we will animate real UI components live during the session.",
    creator: { id: "3", name: "Dr. Sarah Johnson", avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah" },
    start_time: _d(-5, 14),
    duration: 90,
    status: "ended",
    zoom: { meeting_id: "84987654321", password: "xyz789" },
    attendance: { status: "present", minutes_present: 74, percentage: 82, threshold_minutes: 72 },
  },
  {
    id: "m3",
    name: "Node.js & Express Fundamentals",
    description: "Building REST APIs with Node.js, Express, and MongoDB. We will cover routing, middleware, authentication, and connecting to a database.",
    creator: { id: "4", name: "Prof. Michael Chen", avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael" },
    start_time: _d(-10, 9),
    duration: 60,
    status: "ended",
    zoom: { meeting_id: "84111222333", password: "" },
    attendance: { status: "absent", minutes_present: 20, percentage: 33, threshold_minutes: 48 },
  },
  {
    id: "m4",
    name: "Calculus II — Integration Techniques Review",
    description: "A focused review session on integration by parts, trigonometric substitution, and partial fractions before the upcoming exam.",
    creator: { id: "4", name: "Prof. Michael Chen", avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael" },
    start_time: _d(3, 15),
    duration: 45,
    status: "upcoming",
    zoom: { meeting_id: "84444555666", password: "math45" },
    attendance: { status: "pending", minutes_present: 0, percentage: 0, threshold_minutes: 36 },
  },
];

