import {
  StudentCourse,
  StudentLesson,
  StudentAssignment,
  StudentQuiz,
  StudentGrade,
  DiscussionThread,
  CourseAnnouncement,
  ScheduleEvent,
  StudentMessage,
  StudentMaterial,
  StudentProgress,
} from "./student-types";

export const STUDENT_COURSES: StudentCourse[] = [
  {
    id: "cs101",
    name: "Introduction to Computer Science",
    code: "CS101",
    instructor: "Dr. Sarah Johnson",
    thumbnail: "/placeholder.svg?height=200&width=300",
    credits: 3,
    enrollment_date: "2024-01-15",
    status: "active",
    progress: 65,
    grade: "A-",
    gpa: 3.7,
    due_assignments: 2,
    unread_announcements: 3,
  },
  {
    id: "math201",
    name: "Calculus II",
    code: "MATH201",
    instructor: "Prof. Michael Chen",
    thumbnail: "/placeholder.svg?height=200&width=300",
    credits: 4,
    enrollment_date: "2024-01-15",
    status: "active",
    progress: 72,
    grade: "B+",
    gpa: 3.5,
    due_assignments: 1,
    unread_announcements: 1,
  },
  {
    id: "eng102",
    name: "English Literature",
    code: "ENG102",
    instructor: "Dr. Emma Wilson",
    thumbnail: "/placeholder.svg?height=200&width=300",
    credits: 3,
    enrollment_date: "2024-01-15",
    status: "active",
    progress: 58,
    grade: "B",
    gpa: 3.0,
    due_assignments: 3,
    unread_announcements: 2,
  },
];

export const STUDENT_LESSONS: StudentLesson[] = [
  {
    id: "lesson1",
    course_id: "cs101",
    title: "Introduction to Programming",
    description: "Learn the basics of programming and variables",
    type: "video",
    duration: 45,
    is_locked: false,
    completed: true,
    completed_at: "2024-02-01",
    order: 1,
  },
  {
    id: "lesson2",
    course_id: "cs101",
    title: "Data Types and Operations",
    description: "Understand different data types",
    type: "video",
    duration: 38,
    is_locked: false,
    completed: true,
    completed_at: "2024-02-03",
    order: 2,
  },
  {
    id: "lesson3",
    course_id: "cs101",
    title: "Control Flow Basics",
    description: "Master if, else, and loops",
    type: "document",
    duration: 20,
    is_locked: false,
    completed: true,
    completed_at: "2024-02-05",
    order: 3,
  },
  {
    id: "lesson4",
    course_id: "cs101",
    title: "Functions and Scope",
    description: "Learn about functions and variable scope",
    type: "video",
    duration: 52,
    is_locked: false,
    completed: false,
    completed_at: null,
    order: 4,
  },
  {
    id: "lesson5",
    course_id: "cs101",
    title: "Arrays and Lists",
    description: "Work with collections of data",
    type: "video",
    duration: 48,
    is_locked: true,
    completed: false,
    completed_at: null,
    order: 5,
  },
];

export const STUDENT_ASSIGNMENTS: StudentAssignment[] = [
  {
    id: "assign1",
    course_id: "cs101",
    title: "Variables and Operators",
    description: "Create a program using variables and basic operators",
    due_date: "2024-02-08",
    status: "graded",
    submission_date: "2024-02-07",
    grade: 95,
    feedback: "Excellent work! Clean code and well-commented.",
    points_earned: 95,
    total_points: 100,
  },
  {
    id: "assign2",
    course_id: "cs101",
    title: "Control Flow Assignment",
    description: "Implement loops and conditionals",
    due_date: "2024-02-15",
    status: "submitted",
    submission_date: "2024-02-14",
    grade: null,
    feedback: null,
    points_earned: null,
    total_points: 100,
  },
  {
    id: "assign3",
    course_id: "math201",
    title: "Calculus Problem Set",
    description: "Solve 30 calculus problems",
    due_date: "2024-02-12",
    status: "pending",
    submission_date: null,
    grade: null,
    feedback: null,
    points_earned: null,
    total_points: 100,
  },
  {
    id: "assign4",
    course_id: "eng102",
    title: "Essay Analysis",
    description: "Analyze a literary work",
    due_date: "2024-02-10",
    status: "late",
    submission_date: "2024-02-11",
    grade: 85,
    feedback: "Good analysis but submitted late. -5 points penalty.",
    points_earned: 85,
    total_points: 100,
  },
];

export const STUDENT_QUIZZES: StudentQuiz[] = [
  {
    id: "quiz1",
    course_id: "cs101",
    title: "Variables Quiz",
    type: "graded",
    total_questions: 10,
    time_limit: 15,
    attempts_allowed: 2,
    status: "submitted",
    attempts: [
      {
        attempt_number: 1,
        score: 85,
        date_attempted: "2024-02-02",
      },
    ],
    best_score: 85,
  },
  {
    id: "quiz2",
    course_id: "cs101",
    title: "Control Flow Practice",
    type: "practice",
    total_questions: 8,
    time_limit: 10,
    attempts_allowed: 5,
    status: "in_progress",
    attempts: [],
    best_score: null,
  },
  {
    id: "quiz3",
    course_id: "math201",
    title: "Derivatives Practice",
    type: "ungraded",
    total_questions: 15,
    time_limit: 30,
    attempts_allowed: 3,
    status: "not_started",
    attempts: [],
    best_score: null,
  },
];

export const STUDENT_GRADES: StudentGrade[] = [
  {
    course_id: "cs101",
    course_name: "Introduction to Computer Science",
    assignments_grade: 92,
    quizzes_grade: 87,
    participation_grade: 95,
    final_grade: 90.5,
    letter_grade: "A-",
  },
  {
    course_id: "math201",
    course_name: "Calculus II",
    assignments_grade: 85,
    quizzes_grade: 82,
    participation_grade: 88,
    final_grade: 84.2,
    letter_grade: "B+",
  },
  {
    course_id: "eng102",
    course_name: "English Literature",
    assignments_grade: 78,
    quizzes_grade: 80,
    participation_grade: 85,
    final_grade: 80.5,
    letter_grade: "B",
  },
];

export const DISCUSSION_THREADS: DiscussionThread[] = [
  {
    id: "thread1",
    course_id: "cs101",
    title: "How to debug for loop issues?",
    author: "John Doe",
    author_avatar: "/placeholder.svg?height=40&width=40",
    created_at: "2024-02-06",
    replies_count: 12,
    views: 45,
    is_pinned: false,
    has_unread: true,
  },
  {
    id: "thread2",
    course_id: "cs101",
    title: "Assignment 2 clarification",
    author: "Dr. Sarah Johnson",
    author_avatar: "/placeholder.svg?height=40&width=40",
    created_at: "2024-02-05",
    replies_count: 28,
    views: 102,
    is_pinned: true,
    has_unread: false,
  },
  {
    id: "thread3",
    course_id: "math201",
    title: "Integration by parts examples",
    author: "Jane Smith",
    author_avatar: "/placeholder.svg?height=40&width=40",
    created_at: "2024-02-04",
    replies_count: 5,
    views: 23,
    is_pinned: false,
    has_unread: true,
  },
];

export const COURSE_ANNOUNCEMENTS: CourseAnnouncement[] = [
  {
    id: "announce1",
    course_id: "cs101",
    title: "Assignment 2 Due Date Extended",
    content: "The submission deadline for Assignment 2 has been extended to February 15th.",
    instructor: "Dr. Sarah Johnson",
    created_at: "2024-02-06",
    is_read: false,
  },
  {
    id: "announce2",
    course_id: "cs101",
    title: "Midterm Exam Scheduled",
    content: "The midterm exam will be held on March 1st. Please review chapters 1-5.",
    instructor: "Dr. Sarah Johnson",
    created_at: "2024-02-05",
    is_read: true,
  },
  {
    id: "announce3",
    course_id: "math201",
    title: "Office Hours Available",
    content: "I will be holding office hours this Friday from 2-4 PM in room 305.",
    instructor: "Prof. Michael Chen",
    created_at: "2024-02-05",
    is_read: true,
  },
];

export const SCHEDULE_EVENTS: ScheduleEvent[] = [
  {
    id: "event1",
    title: "CS101 Lecture",
    course_id: "cs101",
    course_name: "CS101",
    type: "class",
    start_time: "2024-02-08T10:00:00",
    end_time: "2024-02-08T11:30:00",
    location: "Building A, Room 101",
    description: "Regular lecture session",
  },
  {
    id: "event2",
    title: "Math201 Assignment Due",
    course_id: "math201",
    course_name: "MATH201",
    type: "assignment_due",
    start_time: "2024-02-12T23:59:00",
    end_time: "2024-02-12T23:59:00",
    location: null,
    description: "Calculus Problem Set due by midnight",
  },
  {
    id: "event3",
    title: "Quiz 2: Control Flow",
    course_id: "cs101",
    course_name: "CS101",
    type: "quiz",
    start_time: "2024-02-10T14:00:00",
    end_time: "2024-02-10T14:30:00",
    location: "Online",
    description: "Timed quiz on control flow concepts",
  },
  {
    id: "event4",
    title: "Office Hours",
    course_id: "cs101",
    course_name: "CS101",
    type: "office_hours",
    start_time: "2024-02-09T15:00:00",
    end_time: "2024-02-09T16:30:00",
    location: "Room 205",
    description: "Optional office hours with instructor",
  },
];

export const STUDENT_MESSAGES: StudentMessage[] = [
  {
    id: "msg1",
    sender_id: "instr1",
    sender_name: "Dr. Sarah Johnson",
    sender_avatar: "/placeholder.svg?height=40&width=40",
    content: "Great work on Assignment 1! Your code was clean and well-structured.",
    timestamp: "2024-02-06T14:30:00",
    is_read: true,
    conversation_id: "conv1",
  },
  {
    id: "msg2",
    sender_id: "peer1",
    sender_name: "John Doe",
    sender_avatar: "/placeholder.svg?height=40&width=40",
    content: "Did you understand the for loop explanation in the recent lecture?",
    timestamp: "2024-02-06T10:15:00",
    is_read: false,
    conversation_id: "conv2",
  },
];

export const STUDENT_MATERIALS: StudentMaterial[] = [
  {
    id: "mat1",
    course_id: "cs101",
    name: "Lecture Notes - Chapter 1",
    type: "pdf",
    size: "2.4 MB",
    uploaded_by: "Dr. Sarah Johnson",
    uploaded_date: "2024-02-01",
    download_count: 24,
  },
  {
    id: "mat2",
    course_id: "cs101",
    name: "Programming Examples",
    type: "zip",
    size: "15.2 MB",
    uploaded_by: "Dr. Sarah Johnson",
    uploaded_date: "2024-02-03",
    download_count: 18,
  },
  {
    id: "mat3",
    course_id: "math201",
    name: "Calculus Textbook Chapter 3",
    type: "pdf",
    size: "5.1 MB",
    uploaded_by: "Prof. Michael Chen",
    uploaded_date: "2024-02-02",
    download_count: 31,
  },
];

export const STUDENT_PROGRESS: StudentProgress[] = [
  {
    course_id: "cs101",
    course_name: "Introduction to Computer Science",
    lessons_completed: 3,
    total_lessons: 8,
    assignments_completed: 1,
    total_assignments: 5,
    quizzes_taken: 1,
    total_quizzes: 4,
    overall_progress: 62,
    last_activity: "2024-02-06T14:30:00",
  },
  {
    course_id: "math201",
    course_name: "Calculus II",
    lessons_completed: 4,
    total_lessons: 10,
    assignments_completed: 2,
    total_assignments: 6,
    quizzes_taken: 0,
    total_quizzes: 5,
    overall_progress: 55,
    last_activity: "2024-02-05T10:00:00",
  },
  {
    course_id: "eng102",
    course_name: "English Literature",
    lessons_completed: 2,
    total_lessons: 6,
    assignments_completed: 1,
    total_assignments: 4,
    quizzes_taken: 1,
    total_quizzes: 3,
    overall_progress: 45,
    last_activity: "2024-02-04T16:20:00",
  },
];
