import {
  Student,
  Class,
  Faculty,
  Course,
  Assessment,
  DashboardMetrics,
  Communication,
} from "./tenant-types";

export const mockStudents: Student[] = [
  {
    id: "1",
    name: "Alice Johnson",
    email: "alice@school.com",
    rollNumber: "A-001",
    class: "10-A",
    dateOfBirth: "2008-05-15",
    parentEmail: "parent1@email.com",
    status: "Active",
    joinDate: "2022-04-01",
  },
  {
    id: "2",
    name: "Bob Smith",
    email: "bob@school.com",
    rollNumber: "A-002",
    class: "10-A",
    dateOfBirth: "2008-06-20",
    parentEmail: "parent2@email.com",
    status: "Active",
    joinDate: "2022-04-01",
  },
  {
    id: "3",
    name: "Carol White",
    email: "carol@school.com",
    rollNumber: "A-003",
    class: "10-B",
    dateOfBirth: "2008-07-10",
    parentEmail: "parent3@email.com",
    status: "Active",
    joinDate: "2022-04-01",
  },
  {
    id: "4",
    name: "David Brown",
    email: "david@school.com",
    rollNumber: "A-004",
    class: "10-B",
    dateOfBirth: "2008-08-25",
    parentEmail: "parent4@email.com",
    status: "Inactive",
    joinDate: "2022-04-01",
  },
  {
    id: "5",
    name: "Emma Davis",
    email: "emma@school.com",
    rollNumber: "A-005",
    class: "10-A",
    dateOfBirth: "2008-09-12",
    parentEmail: "parent5@email.com",
    status: "Active",
    joinDate: "2022-04-01",
  },
];

export const mockClasses: Class[] = [
  {
    id: "1",
    name: "10-A",
    grade: "10",
    section: "A",
    classTeacher: "Mr. Sharma",
    totalStudents: 45,
    status: "Active",
    academicYear: "2024-2025",
  },
  {
    id: "2",
    name: "10-B",
    grade: "10",
    section: "B",
    classTeacher: "Ms. Patel",
    totalStudents: 42,
    status: "Active",
    academicYear: "2024-2025",
  },
  {
    id: "3",
    name: "9-A",
    grade: "9",
    section: "A",
    classTeacher: "Mr. Kumar",
    totalStudents: 48,
    status: "Active",
    academicYear: "2024-2025",
  },
  {
    id: "4",
    name: "9-B",
    grade: "9",
    section: "B",
    classTeacher: "Ms. Singh",
    totalStudents: 43,
    status: "Active",
    academicYear: "2024-2025",
  },
];

export const mockFaculty: Faculty[] = [
  {
    id: "1",
    name: "Mr. Rajesh Sharma",
    email: "sharma@school.com",
    phone: "+91-9876543210",
    subjects: ["Mathematics", "Physics"],
    department: "Science",
    joinDate: "2015-06-01",
    role: "Teacher",
    status: "Active",
  },
  {
    id: "2",
    name: "Ms. Priya Patel",
    email: "patel@school.com",
    phone: "+91-9876543211",
    subjects: ["English", "Literature"],
    department: "Language",
    joinDate: "2018-07-15",
    role: "Teacher",
    status: "Active",
  },
  {
    id: "3",
    name: "Mr. Arun Kumar",
    email: "kumar@school.com",
    phone: "+91-9876543212",
    subjects: ["History", "Geography"],
    department: "Social Studies",
    joinDate: "2016-04-10",
    role: "Teacher",
    status: "Active",
  },
  {
    id: "4",
    name: "Mrs. Sneha Singh",
    email: "singh@school.com",
    phone: "+91-9876543213",
    subjects: ["Chemistry", "Biology"],
    department: "Science",
    joinDate: "2019-08-01",
    role: "Teacher",
    status: "Active",
  },
];

export const mockCourses: Course[] = [
  {
    id: "1",
    name: "Mathematics",
    code: "MATH-10",
    grade: "10",
    duration: 240,
    instructor: "Mr. Sharma",
    status: "Active",
    students: 87,
  },
  {
    id: "2",
    name: "English",
    code: "ENG-10",
    grade: "10",
    duration: 180,
    instructor: "Ms. Patel",
    status: "Active",
    students: 87,
  },
  {
    id: "3",
    name: "Science",
    code: "SCI-10",
    grade: "10",
    duration: 240,
    instructor: "Mr. Kumar",
    status: "Active",
    students: 87,
  },
  {
    id: "4",
    name: "History",
    code: "HIST-10",
    grade: "10",
    duration: 120,
    instructor: "Mr. Kumar",
    status: "Active",
    students: 87,
  },
];

export const mockAssessments: Assessment[] = [
  {
    id: "1",
    title: "Mathematics Midterm Exam",
    type: "Exam",
    subject: "Mathematics",
    class: "10-A",
    date: "2025-02-20",
    totalMarks: 100,
    passMarks: 40,
    status: "Scheduled",
  },
  {
    id: "2",
    title: "English Quiz 1",
    type: "Quiz",
    subject: "English",
    class: "10-A",
    date: "2025-02-15",
    totalMarks: 20,
    passMarks: 10,
    status: "Completed",
  },
  {
    id: "3",
    title: "Science Project",
    type: "Project",
    subject: "Science",
    class: "10-B",
    date: "2025-03-01",
    totalMarks: 50,
    passMarks: 25,
    status: "Active",
  },
];

export const mockCommunications: Communication[] = [
  {
    id: "1",
    type: "Announcement",
    title: "School Foundation Day",
    content: "The school foundation day will be celebrated on 15th March",
    sentBy: "Principal",
    sentDate: "2025-02-18",
    recipients: ["All"],
    status: "Published",
  },
  {
    id: "2",
    type: "Alert",
    title: "Holiday Notice",
    content: "School will remain closed on 26th January",
    sentBy: "Admin",
    sentDate: "2025-02-18",
    recipients: ["All"],
    status: "Published",
  },
  {
    id: "3",
    type: "Circular",
    title: "Fee Submission Reminder",
    content: "Please submit your fees by 28th February",
    sentBy: "Accounts",
    sentDate: "2025-02-17",
    recipients: ["Parents"],
    status: "Published",
  },
];

export const mockDashboardMetrics: DashboardMetrics = {
  totalStudents: 178,
  totalFaculty: 24,
  activeClasses: 8,
  totalCourses: 12,
  averageAttendance: 92,
  pendingFees: 15,
};
