import {
  Student,
  Class,
  Faculty,
  Course,
  Assessment,
  DashboardMetrics,
  Communication,
  CourseModule,
  CourseLesson,
  Program,
  Role,
} from "./tenant-types";

export const mockStudents: Student[] = [
  {
    id: "1",
    name: "Alice Johnson",
    email: "alice@school.com",
    rollNumber: "REG-2022-001",
    regNumber: "REG-2022-001",
    class: "2022",
    program: "Bachelor of Science in Computer Science",
    dateOfBirth: "2008-05-15",
    parentEmail: "parent1@email.com",
    status: "Active",
    joinDate: "2022-04-01",
  },
  {
    id: "2",
    name: "Bob Smith",
    email: "bob@school.com",
    rollNumber: "REG-2022-002",
    regNumber: "REG-2022-002",
    class: "2022",
    program: "Bachelor of Science in Computer Science",
    dateOfBirth: "2008-06-20",
    parentEmail: "parent2@email.com",
    status: "Active",
    joinDate: "2022-04-01",
  },
  {
    id: "3",
    name: "Carol White",
    email: "carol@school.com",
    rollNumber: "REG-2023-001",
    regNumber: "REG-2023-001",
    class: "2023",
    program: "Diploma in English Literature",
    dateOfBirth: "2008-07-10",
    parentEmail: "parent3@email.com",
    status: "Active",
    joinDate: "2023-04-01",
  },
  {
    id: "4",
    name: "David Brown",
    email: "david@school.com",
    rollNumber: "REG-2023-002",
    regNumber: "REG-2023-002",
    class: "2023",
    program: "Diploma in English Literature",
    dateOfBirth: "2008-08-25",
    parentEmail: "parent4@email.com",
    status: "Inactive",
    joinDate: "2023-04-01",
  },
  {
    id: "5",
    name: "Emma Davis",
    email: "emma@school.com",
    rollNumber: "REG-2024-001",
    regNumber: "REG-2024-001",
    class: "2024",
    program: "Master of Arts in History",
    dateOfBirth: "2008-09-12",
    parentEmail: "parent5@email.com",
    status: "Active",
    joinDate: "2024-04-01",
  },
];

export const mockClasses: Class[] = [
  {
    id: "1",
    name: "Mathematics 101",
    program: "Computer Science",
    courseCode: "MAT101",
    semester: "Fall Semester",
    instructors: ["Mr. Rajesh Sharma"],
    totalStudents: 45,
    capacity: 60,
    status: "Active",
    academicYear: "2024-2025",
  },
  {
    id: "2",
    name: "Physics Foundations",
    program: "Engineering",
    courseCode: "PHY101",
    semester: "Fall Semester",
    instructors: ["Ms. Priya Patel"],
    totalStudents: 42,
    capacity: 50,
    status: "Active",
    academicYear: "2024-2025",
  },
  {
    id: "3",
    name: "World History",
    program: "Arts & Humanities",
    courseCode: "HIS101",
    semester: "Spring Semester",
    instructors: ["Mr. Arun Kumar"],
    totalStudents: 48,
    capacity: 50,
    status: "Active",
    academicYear: "2024-2025",
  },
  {
    id: "4",
    name: "Business Ethics",
    program: "Business Administration",
    courseCode: "BUS201",
    semester: "Spring Semester",
    instructors: ["Mrs. Sneha Singh"],
    totalStudents: 43,
    capacity: 45,
    status: "Active",
    academicYear: "2024-2025",
  },
];

export const mockFaculty: Faculty[] = [
  {
    id: "1",
    name: "Mr. Rajesh Sharma",
    email: "sharma@school.com",
    phone: "+91-9876543210",
    subjects: ["Mathematics", "Physics"],
    department: "Science",
    joinDate: "2015-06-01",
    role: "Lecturer",
    status: "Active",
    assignedCourses: ["Computer Science (CS-101)", "Mathematics 101"],
    assignedProgram: "Bachelor of Science in Computer Science",
  },
  {
    id: "2",
    name: "Ms. Priya Patel",
    email: "patel@school.com",
    phone: "+91-9876543211",
    subjects: ["English", "Literature"],
    department: "Language",
    joinDate: "2018-07-15",
    role: "Instructor",
    status: "Active",
    assignedCourses: ["Civil Engineering (CE-101)"],
    assignedProgram: "Diploma in English Literature",
  },
  {
    id: "3",
    name: "Mr. Arun Kumar",
    email: "kumar@school.com",
    phone: "+91-9876543212",
    subjects: ["History", "Geography"],
    department: "Social Studies",
    joinDate: "2016-04-10",
    role: "Lecturer",
    status: "Active",
    assignedCourses: ["Political Science (POL-101)"],
    assignedProgram: "Master of Arts in History",
  },
  {
    id: "4",
    name: "Mrs. Sneha Singh",
    email: "singh@school.com",
    phone: "+91-9876543213",
    subjects: ["Chemistry", "Biology"],
    department: "Science",
    joinDate: "2019-08-01",
    role: "Instructor",
    status: "Active",
    assignedCourses: ["Business Administration (BA-101)"],
    assignedProgram: "Bachelor of Science in Computer Science",
  },
];

export const mockCourses: Course[] = [
  {
    id: "1",
    title: "Computer Science",
    code: "CS-101",
    categoryId: "science",
    level: "intermediate",
    language: "english",
    status: "active",
    credits: 4,
    maxStudents: 100,
    enrollmentCount: 87,
    semester: "Fall 2025",
    thumbnail: "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=600",
    description: "Core computer science principles and programming.",
    createdAt: "2025-01-10T10:00:00Z",
  },
  {
    id: "2",
    title: "Civil Engineering",
    code: "CE-101",
    categoryId: "engineering",
    level: "beginner",
    language: "english",
    status: "active",
    credits: 3,
    maxStudents: 100,
    enrollmentCount: 95,
    semester: "Fall 2025",
    thumbnail: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&q=80&w=600",
    description: "Introduction to structural design and civil engineering.",
    createdAt: "2025-01-12T10:00:00Z",
  },
  {
    id: "3",
    title: "Political Science",
    code: "POL-101",
    categoryId: "arts",
    level: "intermediate",
    language: "english",
    status: "active",
    credits: 4,
    maxStudents: 80,
    enrollmentCount: 80, // full
    semester: "Fall 2025",
    thumbnail: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&q=80&w=600",
    description: "Study of political systems and political behavior.",
    createdAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "4",
    title: "Business Administration",
    code: "BA-101",
    categoryId: "business",
    level: "beginner",
    language: "english",
    status: "draft",
    credits: 3,
    maxStudents: 40,
    enrollmentCount: 0,
    semester: "Spring 2026",
    thumbnail: "https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&q=80&w=600",
    description: "Fundamentals of business management and administration.",
    createdAt: "2025-02-01T10:00:00Z",
  },
];

export const mockPrograms: Program[] = [
  {
    id: "1",
    name: "Bachelor of Science in Computer Science",
    description: "A comprehensive program covering computer science fundamentals, programming, and advanced topics.",
    level: "Degree",
    createdBy: "Admin User",
    createdAt: "2025-01-05T08:30:00Z",
    courseIds: ["1", "3"],
  },
  {
    id: "2",
    name: "Diploma in English Literature",
    description: "An intensive diploma program focusing on classic and modern English literature.",
    level: "Diploma",
    createdBy: "Admin User",
    createdAt: "2025-02-10T14:15:00Z",
    courseIds: ["2", "4"],
  },
  {
    id: "3",
    name: "Master of Arts in History",
    description: "Advanced study of world history, geography, and historical analysis.",
    level: "Masters",
    createdBy: "Super Admin",
    createdAt: "2025-03-20T09:45:00Z",
    courseIds: ["4"],
  }
];

export const mockAssessments: Assessment[] = [
  {
    id: "1",
    title: "Mathematics Midterm Exam",
    type: "Exam",
    subject: "Mathematics",
    class: "10-A",
    date: "2025-02-20",
    totalMarks: 100,
    passMarks: 40,
    status: "Scheduled",
  },
  {
    id: "2",
    title: "English Quiz 1",
    type: "Quiz",
    subject: "English",
    class: "10-A",
    date: "2025-02-15",
    totalMarks: 20,
    passMarks: 10,
    status: "Completed",
  },
  {
    id: "3",
    title: "Science Project",
    type: "Project",
    subject: "Science",
    class: "10-B",
    date: "2025-03-01",
    totalMarks: 50,
    passMarks: 25,
    status: "Active",
  },
];

export const mockCommunications: Communication[] = [
  {
    id: "1",
    type: "Announcement",
    title: "School Foundation Day",
    content: "The school foundation day will be celebrated on 15th March",
    sentBy: "Principal",
    sentDate: "2025-02-18",
    recipients: ["All"],
    status: "Published",
  },
  {
    id: "2",
    type: "Alert",
    title: "Holiday Notice",
    content: "School will remain closed on 26th January",
    sentBy: "Admin",
    sentDate: "2025-02-18",
    recipients: ["All"],
    status: "Published",
  },
  {
    id: "3",
    type: "Circular",
    title: "Fee Submission Reminder",
    content: "Please submit your fees by 28th February",
    sentBy: "Accounts",
    sentDate: "2025-02-17",
    recipients: ["Parents"],
    status: "Published",
  },
];

export const mockDashboardMetrics: DashboardMetrics = {
  totalStudents: 178,
  totalFaculty: 24,
  activeClasses: 8,
  totalCourses: 12,
  averageAttendance: 92,
  pendingFees: 15,
};

export const mockRoles: Role[] = [
  {
    id: "1",
    name: "Admin",
    description: "Full system access and administration",
    isSystem: true,
    usersCount: 1,
    scope: "system",
    mfaRequired: true,
    ipRestricted: false,
    sessionTimeout: "1h",
    defaultDashboard: "Admin Dashboard",
    allowedDepartments: ["Administration", "IT Support"],
    permissions: [
      { feature: "Dashboard", actions: ["create", "read", "update", "delete"] },
      { feature: "Programs", actions: ["create", "read", "update", "delete"] },
      { feature: "Courses", actions: ["create", "read", "update", "delete"] },
      { feature: "Classes", actions: ["create", "read", "update", "delete"] },
      { feature: "Students", actions: ["create", "read", "update", "delete"] },
      { feature: "Faculty", actions: ["create", "read", "update", "delete"] },
      { feature: "Finance", actions: ["create", "read", "update", "delete"] },
      { feature: "Reports", actions: ["create", "read", "update", "delete"] },
      { feature: "Roles", actions: ["create", "read", "update", "delete"] },
    ],
  },
  {
    id: "2",
    name: "Tutor",
    description: "Can manage classes, marks, and attendance",
    isSystem: true,
    usersCount: 12,
    scope: "campus",
    mfaRequired: false,
    ipRestricted: false,
    sessionTimeout: "4h",
    defaultDashboard: "Tutor Dashboard",
    allowedDepartments: ["Academics"],
    permissions: [
      { feature: "Dashboard", actions: ["read"] },
      { feature: "Classes", actions: ["read", "update"] },
      { feature: "Students", actions: ["read"] },
      { feature: "Attendance", actions: ["create", "read", "update"] },
      { feature: "Assessments", actions: ["create", "read", "update"] },
    ],
  },
  {
    id: "3",
    name: "Learner",
    description: "Can view grades and academic info",
    isSystem: true,
    usersCount: 178,
    scope: "campus",
    mfaRequired: false,
    ipRestricted: false,
    sessionTimeout: "8h",
    defaultDashboard: "Learner Dashboard",
    allowedDepartments: ["Academics"],
    permissions: [
      { feature: "Dashboard", actions: ["read"] },
      { feature: "Courses", actions: ["read"] },
      { feature: "Classes", actions: ["read"] },
      { feature: "Assessments", actions: ["read"] },
    ],
  },
  {
    id: "4",
    name: "Accountant",
    description: "Can manage financial records",
    isSystem: false,
    usersCount: 2,
    scope: "department",
    mfaRequired: true,
    ipRestricted: true,
    sessionTimeout: "15m",
    defaultDashboard: "Finance Dashboard",
    allowedDepartments: ["Finance"],
    permissions: [
      { feature: "Dashboard", actions: ["read"] },
      { feature: "Finance", actions: ["create", "read", "update", "delete"] },
      { feature: "Reports", actions: ["create", "read"] },
    ],
  },
];
